### ISSUE TITLE
debug apk 安装不上

### ISSUE THREAD

**Issue by lly201** [babysource/VRDroid#2]
debug apk 安装不上

**Comment by babysource** [comment]
是哪个APK？Android机器的版本是不是符合要求？
minSdkVersion.apiLevel = 21
targetSdkVersion.apiLevel = 23

**Comment by lly201** [comment]
系统版本api=22
用的是你上传的apk文件，点击安装无反应

**Comment by babysource** [comment]
我又重新打了个包上传，此次亲测手机可以正常安装，您可以再试试，如果依然有问题，是否您的安装器出问题了！

**Comment by lly201** [comment]
没问题了
